apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.5.1
        ports:
        - containerPort: 5601
        env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch:9200"  # Using HTTP (no SSL) to connect to Elasticsearch
          - name: SERVER_SSL_ENABLED
            value: "false"  # Disable SSL for Kibana itself
          - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
            value: "none"  # Disable SSL verification for Elasticsearch connection
          
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30001
  selector:
    app: kibana
  type: NodePort

