apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
  namespace: logging
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      # Add filters here
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "filebeat-%{+YYYY.MM.dd}"
        ssl => false
      }
      stdout { codec => rubydebug }
    }
